/**
 * Inline SVG icon registry for the Scryb editor chrome.
 *
 * Keys are the legacy Material Symbols names used throughout
 * `MATERIAL_ICONS` and adapter templates, so swapping the renderer does not
 * touch any item config. Values are the inner markup of a 24x24 stroke icon
 * (fill none, stroke currentColor, stroke-width 2 in source; rendered at
 * 1em with stroke-width overridden to 1.5 by the icon components).
 *
 * Icon artwork from Lucide (https://lucide.dev), ISC License,
 * Copyright (c) Lucide Contributors 2022.
 *
 * GENERATED by scratchpad icongen/gen.mjs — regenerate rather than hand-edit
 * path data.
 */

/** Inner SVG markup per legacy Material Symbols icon name. */
export const SCRYB_ICON_PATHS: Record<string, string> = {
  add: '<path d="M5 12h14" /><path d="M12 5v14" />',
  add_column_left: '<rect width="7" height="13" x="3" y="8" rx="1" /><path d="m15 2-3 3-3-3" /><rect width="7" height="13" x="14" y="8" rx="1" />',
  add_column_right: '<rect width="7" height="13" x="3" y="3" rx="1" /><path d="m9 22 3-3 3 3" /><rect width="7" height="13" x="14" y="3" rx="1" />',
  add_row_above: '<rect width="13" height="7" x="8" y="3" rx="1" /><path d="m2 9 3 3-3 3" /><rect width="13" height="7" x="8" y="14" rx="1" />',
  add_row_below: '<rect width="13" height="7" x="3" y="3" rx="1" /><path d="m22 15-3-3 3-3" /><rect width="13" height="7" x="3" y="14" rx="1" />',
  accessibility_new: '<circle cx="12" cy="5" r="1" /><path d="m9 20 3-6 3 6" /><path d="m6 8 6 2 6-2" /><path d="M12 10v4" />',
  arrow_back: '<path d="m12 19-7-7 7-7" /><path d="M19 12H5" />',
  arrow_downward: '<path d="M12 5v14" /><path d="m19 12-7 7-7-7" />',
  arrow_forward: '<path d="M5 12h14" /><path d="m12 5 7 7-7 7" />',
  arrow_upward: '<path d="m5 12 7-7 7 7" /><path d="M12 19V5" />',
  border_left: '<rect width="18" height="18" x="3" y="3" rx="2" /><path d="M9 3v18" />',
  border_top: '<rect width="18" height="18" x="3" y="3" rx="2" /><path d="M3 9h18" />',
  cell_merge: '<path d="M12 21v-6" /><path d="M12 9V3" /><path d="M3 15h18" /><path d="M3 9h18" /><rect width="18" height="18" x="3" y="3" rx="2" />',
  check: '<path d="M20 6 9 17l-5-5" />',
  check_circle: '<circle cx="12" cy="12" r="10" /><path d="m9 12 2 2 4-4" />',
  chevron_right: '<path d="m9 18 6-6-6-6" />',
  checklist: '<path d="M13 5h8" /><path d="M13 12h8" /><path d="M13 19h8" /><path d="m3 17 2 2 4-4" /><path d="m3 7 2 2 4-4" />',
  close: '<path d="M18 6 6 18" /><path d="m6 6 12 12" />',
  cloud_upload: '<path d="M12 13v8" /><path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242" /><path d="m8 17 4-4 4 4" />',
  code: '<path d="m16 18 6-6-6-6" /><path d="m8 6-6 6 6 6" />',
  content_copy: '<rect width="14" height="14" x="8" y="8" rx="2" ry="2" /><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />',
  content_paste: '<rect width="8" height="4" x="8" y="2" rx="1" ry="1" /><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />',
  crop_square: '<rect width="18" height="18" x="3" y="3" rx="2" />',
  delete: '<path d="M10 11v6" /><path d="M14 11v6" /><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /><path d="M3 6h18" /><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />',
  delete_forever: '<path d="M10 11v6" /><path d="M14 11v6" /><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /><path d="M3 6h18" /><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />',
  dock_to_right: '<rect width="18" height="18" x="3" y="3" rx="2" /><path d="M15 3v18" />',
  drag_indicator: '<circle cx="9" cy="12" r="1" /><circle cx="9" cy="5" r="1" /><circle cx="9" cy="19" r="1" /><circle cx="15" cy="12" r="1" /><circle cx="15" cy="5" r="1" /><circle cx="15" cy="19" r="1" />',
  drive_file_rename_outline: '<path d="M13 21h8" /><path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />',
  emoji_emotions: '<circle cx="12" cy="12" r="10" /><path d="M8 14s1.5 2 4 2 4-2 4-2" /><line x1="9" x2="9.01" y1="9" y2="9" /><line x1="15" x2="15.01" y1="9" y2="9" />',
  error: '<circle cx="12" cy="12" r="10" /><line x1="12" x2="12" y1="8" y2="12" /><line x1="12" x2="12.01" y1="16" y2="16" />',
  expand_more: '<path d="m6 9 6 6 6-6" />',
  font_download: '<path d="M12 4v16" /><path d="M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2" /><path d="M9 20h6" />',
  format_align_center: '<path d="M21 5H3" /><path d="M17 12H7" /><path d="M19 19H5" />',
  // Vertical counterparts of the format_align_* set: a rule marking the edge
  // the content is pushed to, and an arrow showing which way it moves.
  vertical_align_top: '<path d="M21 4H3" /><path d="M12 20V8" /><path d="m8 12 4-4 4 4" />',
  vertical_align_center:
    '<path d="M21 12H3" /><path d="M12 3v4" /><path d="m9 6 3 3 3-3" /><path d="M12 21v-4" /><path d="m9 18 3-3 3 3" />',
  vertical_align_bottom: '<path d="M21 20H3" /><path d="M12 4v12" /><path d="m8 12 4 4 4-4" />',
  format_align_justify: '<path d="M3 5h18" /><path d="M3 12h18" /><path d="M3 19h18" />',
  format_align_left: '<path d="M21 5H3" /><path d="M15 12H3" /><path d="M17 19H3" />',
  format_align_right: '<path d="M21 5H3" /><path d="M21 12H9" /><path d="M21 19H7" />',
  format_bold: '<path d="M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8" />',
  format_clear: '<path d="M4 7V4h16v3" /><path d="M5 20h6" /><path d="M13 4 8 20" /><path d="m15 15 5 5" /><path d="m20 15-5 5" />',
  format_color_text: '<path d="M4 20h16" /><path d="m6 16 6-12 6 12" /><path d="M8 12h8" />',
  format_h1: '<path d="M4 12h8" /><path d="M4 18V6" /><path d="M12 18V6" /><path d="m17 12 3-2v8" />',
  format_h2: '<path d="M4 12h8" /><path d="M4 18V6" /><path d="M12 18V6" /><path d="M21 18h-4c0-4 4-3 4-6 0-1.5-2-2.5-4-1" />',
  format_h3: '<path d="M4 12h8" /><path d="M4 18V6" /><path d="M12 18V6" /><path d="M17.5 10.5c1.7-1 3.5 0 3.5 1.5a2 2 0 0 1-2 2" /><path d="M17 17.5c2 1.5 4 .3 4-1.5a2 2 0 0 0-2-2" />',
  format_h4: '<path d="M12 18V6" /><path d="M17 10v3a1 1 0 0 0 1 1h3" /><path d="M21 10v8" /><path d="M4 12h8" /><path d="M4 18V6" />',
  format_h5: '<path d="M4 12h8" /><path d="M4 18V6" /><path d="M12 18V6" /><path d="M17 13v-3h4" /><path d="M17 17.7c.4.2.8.3 1.3.3 1.5 0 2.7-1.1 2.7-2.5S19.8 13 18.3 13H17" />',
  format_h6: '<path d="M4 12h8" /><path d="M4 18V6" /><path d="M12 18V6" /><circle cx="19" cy="16" r="2" /><path d="M20 10c-2 2-3 3.5-3 6" />',
  format_indent_decrease: '<path d="M21 5H11" /><path d="M21 12H11" /><path d="M21 19H11" /><path d="m7 8-4 4 4 4" />',
  format_indent_increase: '<path d="M21 5H11" /><path d="M21 12H11" /><path d="M21 19H11" /><path d="m3 8 4 4-4 4" />',
  format_italic: '<line x1="19" x2="10" y1="4" y2="4" /><line x1="14" x2="5" y1="20" y2="20" /><line x1="15" x2="9" y1="4" y2="20" />',
  format_line_spacing: '<path d="M12 22v-6" /><path d="M12 8V2" /><path d="M4 12H2" /><path d="M10 12H8" /><path d="M16 12h-2" /><path d="M22 12h-2" /><path d="m15 19-3 3-3-3" /><path d="m15 5-3-3-3 3" />',
  format_list_bulleted: '<path d="M3 5h.01" /><path d="M3 12h.01" /><path d="M3 19h.01" /><path d="M8 5h13" /><path d="M8 12h13" /><path d="M8 19h13" />',
  format_list_numbered: '<path d="M11 5h10" /><path d="M11 12h10" /><path d="M11 19h10" /><path d="M4 4h1v5" /><path d="M4 9h2" /><path d="M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02" />',
  format_paragraph: '<path d="M13 4v16" /><path d="M17 4v16" /><path d="M19 4H9.5a4.5 4.5 0 0 0 0 9H13" />',
  format_quote: '<path d="M17 5H3" /><path d="M21 12H8" /><path d="M21 19H8" /><path d="M3 12v7" />',
  format_size: '<path d="m15 16 2.536-7.328a1.02 1.02 1 0 1 1.928 0L22 16" /><path d="M15.697 14h5.606" /><path d="m2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16" /><path d="M3.304 13h6.392" />',
  format_underlined: '<path d="M6 4v6a6 6 0 0 0 12 0V4" /><line x1="4" x2="20" y1="20" y2="20" />',
  functions: '<path d="M18 7V5a1 1 0 0 0-1-1H6.5a.5.5 0 0 0-.4.8l4.5 6a2 2 0 0 1 0 2.4l-4.5 6a.5.5 0 0 0 .4.8H17a1 1 0 0 0 1-1v-2" />',
  horizontal_rule: '<path d="M5 12h14" />',
  image: '<rect width="18" height="18" x="3" y="3" rx="2" ry="2" /><circle cx="9" cy="9" r="2" /><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />',
  keyboard_return: '<path d="M20 4v7a4 4 0 0 1-4 4H4" /><path d="m9 10-5 5 5 5" />',
  link: '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" /><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />',
  link_off: '<path d="m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71" /><path d="m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71" /><line x1="8" x2="8" y1="2" y2="5" /><line x1="2" x2="5" y1="8" y2="8" /><line x1="16" x2="16" y1="19" y2="22" /><line x1="19" x2="22" y1="16" y2="16" />',
  more_vert: '<circle cx="12" cy="12" r="1" /><circle cx="19" cy="12" r="1" /><circle cx="5" cy="12" r="1" />',
  more_horiz: '<circle cx="12" cy="12" r="1" /><circle cx="19" cy="12" r="1" /><circle cx="5" cy="12" r="1" />',
  open_in_browser: '<rect x="2" y="4" width="20" height="16" rx="2" /><path d="M10 4v4" /><path d="M2 8h20" /><path d="M6 4v4" />',
  open_in_new: '<path d="M15 3h6v6" /><path d="M10 14 21 3" /><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />',
  palette: '<path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" /><circle cx="13.5" cy="6.5" r=".5" fill="currentColor" /><circle cx="17.5" cy="10.5" r=".5" fill="currentColor" /><circle cx="6.5" cy="12.5" r=".5" fill="currentColor" /><circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />',
  photo_size_select_actual: '<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" /><path d="M14 15H9v-5" /><path d="M16 3h5v5" /><path d="M21 3 9 15" />',
  redo: '<path d="m15 14 5-5-5-5" /><path d="M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13" />',
  refresh: '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" /><path d="M21 3v5h-5" /><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" /><path d="M8 16H3v5" />',
  search: '<path d="m21 21-4.34-4.34" /><circle cx="11" cy="11" r="8" />',
  segment: '<path d="M21 5H3" /><path d="M15 12H3" /><path d="M17 19H3" />',
  smart_display: '<path d="M15.033 9.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56V7.648a.645.645 0 0 1 .967-.56z" /><path d="M12 17v4" /><path d="M8 21h8" /><rect x="2" y="3" width="20" height="14" rx="2" />',
  split_scene: '<path d="M12 15V9" /><path d="M3 15h18" /><path d="M3 9h18" /><rect width="18" height="18" x="3" y="3" rx="2" />',
  strikethrough_s: '<path d="M16 4H9a3 3 0 0 0-2.83 4" /><path d="M14 12a4 4 0 0 1 0 8H6" /><line x1="4" x2="20" y1="12" y2="12" />',
  subscript: '<path d="m4 5 8 8" /><path d="m12 5-8 8" /><path d="M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07" />',
  superscript: '<path d="m4 19 8-8" /><path d="m12 19-8-8" /><path d="M20 12h-4c0-1.5.442-2 1.5-2.5S20 8.334 20 7.002c0-.472-.17-.93-.484-1.29a2.105 2.105 0 0 0-2.617-.436c-.42.239-.738.614-.899 1.06" />',
  swap_horiz: '<path d="M8 3 4 7l4 4" /><path d="M4 7h16" /><path d="m16 21 4-4-4-4" /><path d="M20 17H4" />',
  table_chart: '<path d="M12 3v18" /><rect width="18" height="18" x="3" y="3" rx="2" /><path d="M3 9h18" /><path d="M3 15h18" />',
  table_view: '<path d="M12 3v18" /><rect width="18" height="18" x="3" y="3" rx="2" /><path d="M3 9h18" /><path d="M3 15h18" />',
  text_fields: '<path d="m18 8 4 4-4 4" /><path d="M2 12h20" /><path d="m6 8-4 4 4 4" />',
  title: '<path d="M6 12h12" /><path d="M6 20V4" /><path d="M18 20V4" />',
  toolbar: '<rect width="18" height="18" x="3" y="3" rx="2" /><path d="M3 9h18" />',
  undo: '<path d="M9 14 4 9l5-5" /><path d="M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11" />',
  visibility: '<path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" /><circle cx="12" cy="12" r="3" />',
  visibility_off: '<path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49" /><path d="M14.084 14.158a3 3 0 0 1-4.242-4.242" /><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143" /><path d="m2 2 20 20" />',
  warning: '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" /><path d="M12 9v4" /><path d="M12 17h.01" />',
  info: '<circle cx="12" cy="12" r="10" /><path d="M12 16v-4" /><path d="M12 8h.01" />',
  edit: '<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" /><path d="m15 5 4 4" />',
};

/**
 * Look up the inline SVG markup for an icon name.
 *
 * @param name - Legacy Material Symbols icon name (e.g. "format_bold")
 * @returns Inner SVG markup, or null when the name has no SVG equivalent
 *   (callers fall back to the ligature font span)
 */
export function getScrybIconPath(name: string): string | null {
  // Own-property check, not a bare index: the return value is handed straight to
  // innerHTML / dangerouslySetInnerHTML, and a bare index on an object literal
  // resolves "constructor" or "toString" to an inherited Object.prototype value.
  return Object.hasOwn(SCRYB_ICON_PATHS, name) ? (SCRYB_ICON_PATHS[name] as string) : null;
}
